# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflow3', '0012_auto_20200325_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskflowinstance',
            name='create_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='创建任务额外信息（App maker ID或APP CODE或周期任务ID）'),
        ),
    ]
