# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-29 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_uploadticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadticket',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='wether this ticket is available'),
        ),
    ]
